# The program should then find a combination of dishes that has a total of exactly the target price.
# If there is no solution found, then the program should print that there is no combination of dishes that is equal to the target price.
# The program must run with different data files generated by us in the same format, so provide instructions on github.com on how to run the program from command line with command line parameters to read alternative input file.

import json
# Load JSON menu:
print("Please enter the file path of your menu:\n(File must be in JSON format)")
menu = str(input())
with open(menu) as json_file:
    prices = json.load(json_file)

# Load target price:
print("Please enter your target price:")
yourprice = float(input())

class Order(object):
   def combinationSum(self, menu, to_spend):
      dishes = []
      unique = {}
      menuprices = list(set(menu.values()))
      self.solve(menuprices, to_spend, dishes, unique)
      return dishes
   def solve(self, menuprices, to_spend, dishes, unique, i = 0, current = []):
      if to_spend == 0:
         temp = [i for i in current]
         temp1 = temp
         temp.sort()
         temp = tuple(temp)
         if temp not in unique:
            unique[temp] = 1
            dishes.append(temp1)
         return
      if to_spend < 0:
         return
      for x in range(i, len(menuprices)):
         current.append(menuprices[x])
         self.solve(menuprices, to_spend - menuprices[x], dishes, unique, i, current)
         current.pop(len(current) - 1)

ord = Order()
order = ord.combinationSum(prices, yourprice)
menuprices = list(set(prices.values()))
menudishes = list(prices.keys())

if order == []:
    print("There's no combination of dishes that matches your target price.")
else:
    print("You can order the following combinations of dishes:")
    for i in range(len(order)):
        option = order[i]
        for i in range(len(option)):
            idx = menuprices.index(option[i])
            print(f"{menudishes[idx]} : ${option[i]}")
        if len(order) > 1:
            print(" ")
